### PR TITLE
Sync push image and enable experimental features

### PR DESCRIPTION
**Pull request by pacostas**
## Merge After
* https://github.com/paketo-buildpacks/github-config/pull/887
* https://github.com/paketo-buildpacks/github-config/pull/888

## Summary

This PR:
* syncs `push-image.yml` file with one form github-config repo
* Enables the experimental features from the `options.json`
 
## Checklist

* [x] I have viewed, signed, and submitted the Contributor License Agreement.
* [ ] I have linked issue(s) that this PR should close using keywords or the Github UI (See [docs](https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue))
* [x] I have added an integration test, if necessary.
* [x] I have reviewed the [styleguide](https://github.com/paketo-buildpacks/community/blob/main/STYLEGUIDE.md) for guidance on my code quality.
* [x] I'm happy with the commit history on this PR (I have rebased/squashed as needed).

### CODE REVIEW

**Comment by pacostas** [comment]
@ForestEckhardt it has to be merged after 
https://github.com/paketo-buildpacks/github-config/pull/887
https://github.com/paketo-buildpacks/github-config/pull/888

**Review by mhdawson — APPROVED** [review]
LGTM

**Comment by pacostas** [comment]
@mhdawson rebased.

**Review by mhdawson — APPROVED** [review]
LGTM

**Pull request merged**
